# 工作流名
name: github pages deploy
# 触发条件
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# 任务
jobs:
  # 一个部署pages的任务
  deloy-pages:
    # 运行runner
    runs-on: ubuntu-latest

    # 执行步骤
    steps:
    # checkout仓库，才能进行后续操作
    - name: checkout 
      uses: actions/checkout@v2

    # hugo生成静态文件
    - name: hugo-setup
      uses: peaceiris/actions-hugo@v2.4.12

    # 部署pages
    - name: deploy-pages
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        publish_branch: gh-pages
        publish_dir: .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
